---
- name: Converge
  hosts: all
  roles:
    - role: ome.omero_web
      omero_web_ice_version: "3.6"

    - role: ansible-role-omero-web-apps
      omero_web_apps_packages:
        - omero-mapr
      omero_web_apps_names:
        - omero_mapr
      omero_web_apps_top_links:
        - label: OMERO
          link:
            viewname: webindex
            query_string: {experimenter: -1}
          attrs:
            title: Image Data Repository
        - label: Genes
          link:
            viewname: maprindex_gene
            query_string: {experimenter: -1}
          attrs:
            title: Genes browser
      omero_web_apps_config_append:
        omero.web.mapr.config:
          - menu: "gene"
            config:
              default:
                - "Gene Symbol"
              all:
                - "Gene Symbol"
                - "Gene Identifier"
              ns:
                - "openmicroscopy.org/mapr/gene"
              label: "Gene"
              case_sensitive: true
          - menu: "genesupplementary"
            config:
              default: []
              all: []
              ns:
                - "openmicroscopy.org/mapr/gene/supplementary"
              label: "Gene supplementary"
      omero_web_apps_config_set:
        example.string: example value
        example.boolean: true
        example.integer: 2
